from __future__ import annotations

from .evaluation import EvalCase
from .index import RetrievalIndex

DOCUMENTS: dict[str, str] = {
    "concurrency": """# Bounded Concurrency

Use a semaphore to bound how many requests run at once against a downstream
provider, protecting both the process and the dependency from overload.

# Retries

Retry transient failures with capped exponential backoff and jitter so
synchronized retries do not turn a blip into an outage.
""",
    "distributed": """# Idempotency

An idempotent handler produces the same result no matter how many times a
duplicate delivery replays it, which is what makes at-least-once delivery safe.

# Backpressure

When a consumer falls behind, a producer must block, shed load, or buffer
within a bound rather than growing an unbounded queue.
""",
    "agents": """# Tool Execution

Treat tool arguments as untrusted input generated by a model, and validate
them against a schema before a handler ever runs.

# Multi-Agent Coordination

Separate durable workflow state from transient messages, and give each agent
a narrowly scoped set of credentials for the task at hand.
""",
    "mcp": """# Multi-Tenancy

A shared server must resolve every request's tenant from an authenticated
identity, never from a client-supplied field in the request body.

# Schema Versioning

Keep old tool schema versions registered alongside new ones so a client that
has not upgraded yet keeps working during a deprecation window.
""",
}


def build_demo_index() -> RetrievalIndex:
    index = RetrievalIndex()
    for document_id, text in DOCUMENTS.items():
        index.add_document(document_id, text)
    return index


def build_demo_eval_cases() -> list[EvalCase]:
    return [
        EvalCase("how do I bound concurrent requests", frozenset({"concurrency#0"})),
        EvalCase("avoiding retry storms", frozenset({"concurrency#1"})),
        EvalCase(
            "safe handling of duplicate message delivery", frozenset({"distributed#0"})
        ),
        EvalCase("what happens when a consumer falls behind", frozenset({"distributed#1"})),
        EvalCase("validating tool call arguments from a model", frozenset({"agents#0"})),
        EvalCase("scoping agent credentials narrowly", frozenset({"agents#1"})),
        EvalCase("resolving tenant identity on a shared server", frozenset({"mcp#0"})),
        EvalCase("keeping old tool versions working for old clients", frozenset({"mcp#1"})),
    ]
